title: IframeApps
modelClass: Wpjscc\Js\Models\IframeApp
list: $/wpjscc/js/models/jsapp/iframe.yaml
recordUrl: ''
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
# showSetup: true
# showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc
# toolbar:
#     buttons: list_toolbar
#     search:
#         prompt: 'backend::lang.list.search_prompt'
