list: $/wpjscc/js/models/jsapp/columns.yaml
modelClass: Wpjscc\Js\Models\JsApp
title: Apps
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'wpjscc/js/apps/update/:id'
