title: IframeApps
modelClass: Wpjscc\Js\Models\IframeApp
list: $/wpjscc/js/models/iframeapp/columns.yaml
recordUrl: 'wpjscc/js/iframeapps/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
